version: '3.9'

services:
  jupyter:
    user: root
    container_name: jupyter
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
    command: "jupyterhub --config=jupyterhub_config.py"
